name: Daily Run for D with Telegram bot

on:
  schedule:
    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: daily_execution_d_telegram_bot

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        environment-file: environment.yml
        activate-environment: botwenger 
        channels: conda-forge

    - name: Run Daily Botwenger script to Telegram Bot for D
      run: conda run -n botwenger python botwenger/modeling/predict.py
